### ISSUE TITLE
Update repo summary

### ISSUE THREAD

**Issue by elithrar** [goji/context#2]
"Goji integration for code.google.com/p/go.net/context" should become (e.g.) "code.google.com/p/go.net/context support for Goji 1" to make it clearer the 'superseded' nature of this package.

(I might submit a PR for the README as well, if you're in agreement with the above suggestion @zenazn)

**Comment by zenazn** [comment]
Done!

**Comment by zenazn** [comment]
(slightly different text, but same intent)

**Comment by elithrar** [comment]
Better than my suggestion anyway :100:
